### PR TITLE
Add Perl library

### PR DESCRIPTION
**Pull request by dracos**
This should implement the spec and tests from https://github.com/sqids/sqids-spec

### CODE REVIEW

**Comment by 4kimov** [comment]
Hi @dracos,

That's great, thank you for the work and for pinging about this!

Do you see anything else that's left to adjust -- perhaps some URLs can now be changed to official repo in `META.json`?
~Also, should this be published as a module?~ (edit: just saw you [published](https://metacpan.org/pod/Sqids) it 👍 )

I've sent you a maintainer invite so you can push whenever you'd like.

**Comment by dracos** [comment]
Thanks! Yes, I've just updated the URLs in the metadata, and a couple of documentation typographical issues.

Where is the sqids.org website code? I saw perl had been activated there, thanks, it has one typo in the last example, `alphabet:` needs to be `alphabet =>` is all :)

**Comment by 4kimov** [comment]
@dracos Cool.

The website is not oss, but I got the example from the readme: https://github.com/sqids/sqids-perl?tab=readme-ov-file#new under the **alphabet** section.

Should it be this?

```perl
my $sqids = Sqids->new( alphabet => 'k3G7QAe51FCsPW92uEOyq4Bg6Sp8YzVTmnU0liwDdHXLajZrfxNhobJIRcMvKt' );
```

Edit: Changed double quotes for single.

**Comment by dracos** [comment]
Oh dear! Yes it should. I'll fix that now 😊

**Pull request merged**
